version: "3.9"  
services:
  fastapi:
    image: jaimeiacenter/clase_devops:myimagefastapiv3
    build: ./docker_fastapi
    ports:
      - "80:80"
    depends_on:
      - mysql
  mysql:
    image: jaimeiacenter/clase_devops_mysql:myimagemysqlv1
    build: ./docker_mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      # left side port = host | right side port = container
      - "3306:3306"