version: "3.9"  
services:
  fastapi:
    image: fernando1206/clasedevops:myimagev3
    build: ./docker_fastapi
    ports:
      - "80:80"
    depends_on:
      - mysql
  mysql:
    image: fernando1206/clasedevops_mysql:myimagemysqlv1
    build: ./docker_mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    #left port is host , right port is container
    ports:
      - "3306:3306"