version: "3.9"  
services:
  fastapi:
    image: fernando1206/clasedevops:myimagev3
    build: ./docker_fastapi
    ports:
      - "80:80"
    links:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: root
  db:
    image: mysql:oracle
    command: --default-authentication-plugin=mysql_native_password
    #left port is host , right port is container
    ports:
      - "3306:3306"
    volumes:
      - ./dbfiles:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fastapi
      